title: "Amin Huseynli - Portfolio"
email: "your.email@example.com"
description: "Personal portfolio showcasing projects and background."
baseurl: "/extremoly" # change if deploying to username.github.io/repo
url: "https://extremoly.github.io/extremoly" # your site URL, e.g., https://username.github.io
theme: minima
plugins: [jekyll-feed]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

